approval_policy = "never"
sandbox_mode = "workspace-write"

model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"

show_raw_agent_reasoning = true

[sandbox_workspace_write]
network_access = true

[features]
web_search_request = true
shell_snapshot = true
shell_tool = true
undo = true

[projects."/Users/anthony/code/decrypto-discord"]
trust_level = "trusted"

[projects."/Users/anthony/code/personal-assistant"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
